CREATE DATABASE XYZ;
USE XYZ;

CREATE TABLE EMPLOYEE_INFO(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY INT NOT NULL);

INSERT INTO EMPLOYEE_INFO VALUES
(1,"ADAM",25000),
(2,"BOB",30000),
(3,"CASEY",40000);
SELECT * FROM EMPLOYEE_INFO;

